
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package calculatorParser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 5;
  public static final int NUMBER = 6;
  public static final int LPAR = 2;
  public static final int MULTIPLY = 4;
  public static final int RPAR = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAR",
  "RPAR",
  "MULTIPLY",
  "PLUS",
  "NUMBER"
  };
}

