
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package calculatorParser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int DIVIDE = 7;
  public static final int NUMBER = 10;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int MODULO = 8;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int TIMES = 4;
  public static final int INVERSEMODULO = 9;
  public static final int LPAREN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "TIMES",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "MODULO",
  "INVERSEMODULO",
  "NUMBER"
  };
}

